#======================================
# Governor by ShermansWorld
# An Unofficial Towny Expansion Plugin
#======================================

config-version: 1

# =====================================
# |          TAX CALL SETTINGS        |
# =====================================

# Tax calls are an alternative taxing method directed towards online players

TownTax:

  CallTime: 6000
  # How long the tax call will last in ticks
  # 1 second = 20, 1 min = 1200. Default = 5 minutes (6000)
  # Server restarts/reloads will cancel tax calls, so this shouldn't be set too high
  
  MaxTaxAmount: 10000
  # The maximum tax amount allowed. Default = $10,000
  
  AskCaller: false
  # If the person who started the tax will also be asked to pay it
  
  AllowedRanks:
    - "co-mayor"
    - "assistant"
    #- "guard"
    #- "helper"
    #- "sheriff"
    
  #The towny ranks allowed to start a town tax call
  #The town mayor is always allowed to start a tax call
   
NationTax:

  CallTime: 6000
  # How long the tax call will last in ticks
  # 1 second = 20, 1 min = 1200. Default = 5 minutes (6000)
  # Server restarts/reloads will cancel tax calls, so this shouldn't be set too high
  MaxTaxAmount: 10000
  # The maximum tax amount allowed. Default = $10,000
  
  AskCaller: false
  # If the person who started the tax will also be asked to pay it
  
  AllowedRanks:
    - "assistant"
    #- "captain"
    #- "colonel"
    #- "engineer"
    #- "general"
    #- "gunner"
    #- "helper"
    #- "lieutenant"
    #- "major"
    #- "private"
    
# =====================================
# |     CHAIN-OF-COMMAND SETTINGS     |
# =====================================

# Chain-of-Command is a feature that allows players to claim the leadership of inactive towns
# When a player claims leadership, they will automatically become mayor and the former leader co-mayor

ChainOfCommand:

  Enabled: true
  # Enables/Disables the entire Chain-of-Comamnd feature 
   
  InactiveTime: 30
  # How many days a leader must be inactive for a town's leadership to be claimed
  # Default = 30 days
  
  AnyoneCanClaim: false
  # This allows ALL players to claim a town if it is deemed inactive (USE WITH CAUTION)
  # Overrides all other options
  
  AnyNationMemberCanClaim: false
  # Nation members can assume control, even if they are not in the town
  # Allows for town members to claim as well
  
  AnyTownMemberCanClaim: false
  # Town members can assume control regardless of their towny rank
  
  AllowedRanks:
    - "co-mayor"
    - "assistant"
    #- "guard"
    #- "helper"
    #- "sheriff"
  
  # Player can assume control of the town if they have these towny ranks
  # Only matters if the other claim conditions are false
  
  
 

