name: Governor
version: 1.2.2
api-version: 1.18
author: ShermansWorld
main: me.ShermansWorld.Governor.Governor
depend: [Vault, Towny]
softdepend: [Essentials, ChestShop, Jobs, QuickShop]

commands:
  governor:
    description: Tax every online player on the server within a town or nation
    depend: [Vault, Towny]
  ttax:
    description: Accepts or denies a town tax
    depend: [Vault, Towny]
  ntax:
    description: Accepts or denies a nation tax
    depend: [Vault, Towny]